services:
  database:
    image: 'postgres:15.0'
    ports:
      - '${DATABASE_EXPOSE}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - '${WEB_EXPOSE}:${WEB_PORT}'
    environment:
      SOVOK_SERVER_PORT: ${WEB_PORT}
      SOVOK_DATABASE_URL: ${WEB_DATABASE_URL}
      SOVOK_SERVER_JWT_SECRET: ${WEB_JWT_SECRET}

      SOVOK_AWS_ACCESS_KEY: ${WEB_AWS_ACCESS_KEY}
      SOVOK_AWS_SECRET_KEY: ${WEB_AWS_SECRET_KEY}
      SOVOK_AWS_SERVER: ${WEB_AWS_SERVER}
      SOVOK_AWS_BUCKET: ${WEB_AWS_BUCKET}
      SOVOK_AWS_SSL_ENABLED: ${WEB_AWS_SSL_ENABLED}

      SOVOK_TMP_PATH: ${WEB_TMP_PATH}
      SOVOK_CDN_BASE_URL: ${WEB_CDN_BASE_URL}

      SOVOK_MUSICBRAINZ_APPNAME: ${WEB_MUSICBRAINZ_APPNAME}
      SOVOK_MUSICBRAINZ_APPVERSION: ${WEB_MUSICBRAINZ_APPVERSION}
      SOVOK_MUSICBRAINZ_CONTACT: ${WEB_MUSICBRAINZ_CONTACT}

volumes:
  database_data:
